language: php
php:
  - 5.3

before_install:
  - BRANCH=`git branch 2>/dev/null | grep "^ " | cut -c3-`
  - git clone git://github.com/novius-os/ci.git
  - cd ci
  - git checkout $BRANCH
  - cd ..

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -p -s --standard=ci/phpcs/ruleset.xml ./


